type Exchange = {
  name: string;
  currency: string;
};

export const EXCHANGES: Exchange[] = [
  { name: 'Shenzhen', currency: 'CNY' },
  { name: 'KSE', currency: 'PKR' },
  { name: 'HKSE', currency: 'HKD' },
  { name: 'Kuala Lumpur', currency: 'MYR' },
  { name: 'KOSDAQ', currency: 'KRW' },
  { name: 'Taiwan', currency: 'TWD' },
  { name: 'Frankfurt Stock Exchange', currency: 'EUR' },
  { name: 'London Stock Exchange', currency: 'GBP' },
  { name: 'Hong Kong Stock Exchange', currency: 'HKD' },
  { name: 'Frankfurt', currency: 'EUR' },
  { name: 'Warsaw Stock Exchange', currency: 'PLN' },
  { name: 'Bombay Stock Exchange', currency: 'INR' },
  { name: 'International Order Book', currency: 'USD' },
  { name: 'Stuttgart', currency: 'EUR' },
  { name: 'Berlin', currency: 'EUR' },
  { name: 'Hamburg', currency: 'EUR' },
  { name: 'OTC Markets OTCPK', currency: 'USD' },
  { name: 'Other OTC', currency: 'USD' },
  { name: 'Tokyo', currency: 'JPY' },
  { name: 'Stock Exchange of Singapore', currency: 'SGD' },
  { name: 'Toronto Stock Exchange', currency: 'CAD' },
  { name: 'Swiss Exchange', currency: 'CHF' },
  { name: 'Munich', currency: 'EUR' },
  { name: 'IOB', currency: 'USD' },
  { name: 'Paris', currency: 'EUR' },
  { name: 'Saudi', currency: 'SAR' },
  { name: 'Taipei Exchange', currency: 'TWD' },
  { name: 'Australian Securities Exchange', currency: 'AUD' },
  { name: 'Amsterdam', currency: 'EUR' },
  { name: 'Dusseldorf', currency: 'EUR' },
  { name: 'Milan', currency: 'EUR' },
  { name: 'Vienna', currency: 'EUR' },
  { name: 'Oslo Stock Exchange', currency: 'NOK' },
  { name: 'National Stock Exchange of India', currency: 'INR' },
  { name: 'Thailand', currency: 'THB' },
  { name: 'Stockholm Stock Exchange', currency: 'SEK' },
  { name: 'XETRA', currency: 'EUR' },
  { name: 'Madrid Stock Exchange', currency: 'EUR' },
  { name: 'Budapest', currency: 'HUF' },
  { name: 'Johannesburg', currency: 'ZAR' },
  { name: 'Shanghai', currency: 'CNY' },
  { name: 'BSE', currency: 'INR' },
  { name: 'Irish', currency: 'EUR' },
  { name: 'New York Stock Exchange', currency: 'USD' },
  { name: 'New York Stock Exchange Arca', currency: 'USD' },
  { name: 'Nasdaq', currency: 'USD' },
  { name: 'Athens', currency: 'EUR' },
  { name: 'Copenhagen', currency: 'DKK' },
  { name: 'NASDAQ', currency: 'USD' },
  { name: 'NASDAQ Global Market', currency: 'USD' },
  { name: 'NASDAQ Global Select', currency: 'USD' },
  { name: 'NASDAQ Capital Market', currency: 'USD' },
  { name: 'Toronto Stock Exchange Ventures', currency: 'CAD' },
  { name: 'Jakarta Stock Exchange', currency: 'IDR' },
  { name: 'Helsinki', currency: 'EUR' },
  { name: 'São Paulo', currency: 'BRL' },
  { name: 'American Stock Exchange', currency: 'USD' },
  { name: 'TSXV', currency: 'CAD' },
  { name: 'Mexico', currency: 'MXN' },
  { name: 'NEO', currency: 'CAD' },
  { name: 'Cboe US', currency: 'USD' },
  { name: 'OTC Markets OTCQX', currency: 'USD' },
  { name: 'Buenos Aires', currency: 'ARS' },
  { name: 'Brussels', currency: 'EUR' },
  { name: 'Tel Aviv', currency: 'ILS' },
  { name: 'Moscow Stock Exchange', currency: 'RUB' },
  { name: 'Canadian Securities Exchange', currency: 'CAD' },
  { name: 'NZSE', currency: 'NZD' },
  { name: 'Canadian Sec', currency: 'CAD' },
  { name: 'Istanbul Stock Exchange', currency: 'TRY' },
  { name: 'Santiago', currency: 'CLP' },
  { name: 'Qatar', currency: 'QAR' },
  { name: 'OTC Markets EXMKT', currency: 'USD' },
  { name: 'OTC Markets OTCQB', currency: 'USD' },
  { name: 'Dubai', currency: 'AED' },
  { name: 'Lisbon', currency: 'EUR' },
  { name: 'Cboe CA', currency: 'CAD' },
  { name: 'CBOE BZX', currency: 'USD' },
  { name: 'NASDAQ Stock Market', currency: 'USD' },
  { name: 'BATS', currency: 'USD' },
  { name: 'Cboe Europe', currency: 'EUR' },
  { name: 'Nordic Growth Market', currency: 'SEK' },
  { name: 'Kuwait', currency: 'KWD' },
  { name: 'Iceland', currency: 'ISK' },
  { name: 'Prague', currency: 'CZK' },
  { name: 'EGX', currency: 'EGP' },
  { name: 'Aquis AQSE', currency: 'GBP' },
  { name: 'HOSE', currency: 'VND' },
  { name: 'Riga', currency: 'EUR' },
  { name: 'NASDAQ Stock Exchange', currency: 'USD' },
  { name: 'BVC', currency: 'COP' },
  { name: 'Cboe BZX Exchange', currency: 'USD' },
];
